  name: convert-file
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo content
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: pip install
          run: pip install -r ./script/requirements.txt
        - name: execute convert
          run: |
            python ./script/github_action.py 