  name: convert-file
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo content
          uses: actions/checkout@v2
          with:
            ssh-key: ${{ secrets.SUBMODULE_OBSIDIAN }}
            submodules: 'recursive'
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: pip install
          run: pip install -r ./script/requirements.txt
        - name: execute convert
          run: |
            python ./script/github_action.py
        - name: Check for change
          run: git status
        - name: stage changed files
          run: git add .
        - name: Commit
          run: git commit -m "Auto update blog"
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: fetch from GitAction
          run: git fetch origin GitAction
        - name: push
          run: git push origin HEAD:GitAction