  name: convert-file
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo content
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: pip install
          run: pip install -r ./script/requirements.txt
        - name: execute convert
          run: |
            python ./script/github_action.py
        - name: add github environ
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
        - name: Check for change
          run: git status
        - name: stage changed files
          run: git add .
        - name: Git
          run: git commit -m "Auto update blog"
        - name: fetch from GitAction
          run: git fetch origin GitActions
        - name: push
          run: git push origin HEAD:GitActions